name: Deploy to dev Amazon ECS

run-name: Deploy to dev by @${{ github.actor }}


on:
  push:
    branches:
      - main
      - master


jobs:
  call-reusable-workflow:
    uses: ./github/workflows/reusable-workflow.yml
    with:
      stage: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
